### ISSUE TITLE
Object is displaced if origin is not in the same location as the empty it is parented to

### ISSUE THREAD

**Issue by mraware** [portify/io_scene_dts#18]
Here are some screenshots along with a temporary fix for the issue: http://imgur.com/a/1mFaz
The orange dot in the first two pictures represents the object's origin. This fix requires you to disable "Use mesh transforms" when exporting.

A similar problem occurs for this guy: http://forum.blockland.us/index.php?topic=293830.0
He just didn't disable "Use mesh transforms"

**Comment by qoh** [comment]
What "Use mesh transforms" is supposed to do is to apply object-local location, rotation and scale (relative to the parent empty), because DTS does not support that (it's basically just supposed to apply those properties to the mesh, relative to the parent). I find that it often doesn't work though, so it should probably be off by default (until myself or somebody figures out why).

**Comment by qoh** [comment]
Partially fixed by 8500708, that option is now off by default.

**Comment by qoh** [comment]
Can you confirm that Use mesh transforms works as expected as of 66a15d17? Exporting your mesh should work fine regardless of it being checked or not now.

**Comment by qoh** [comment]
Closing for now, feel free to reopen.
