### ISSUE TITLE
Exporting over the default player model muddles up avatar customization in multiplayer

### ISSUE THREAD

**Issue by ghost** [portify/io_scene_dts#39]
1. Import m.dts, modify it or leave it as the original.
2. Export m.dts over the original
3. Join a server, instead of a familiar face you'll see an abomination in its place.
4. Start a singleplayer session, you'll be normal again.

![](http://i.imgur.com/JFmPE3Z.png)

![](http://i.imgur.com/tME0P1a.png)

**Comment by qoh** [comment]
@Klocko This is because the server is sending node visibility and colors using indices into the model, as it expects you to have the same DTS file as the server. Since you don't, things are not necessarily the same. Thus you get the wrong nodes being shown and colored. This is not really an issue with this plugin.
